#trigger:
#- main

#pool:
#  name: private

#variables:
#  buildConfiguration: 'Release'
#  solution: '**/*.sln'
#  publishDir: '$(Build.ArtifactStagingDirectory)\_PublishedWebApp'

#steps:
#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    msbuildArgs: '/p:DeployOnBuild=true /p:PublishProfile="" /p:WebPublishMethod=FileSystem /p:PublishDir=$(publishDir)\ /p:Configuration=$(buildConfiguration)'
#    platform: 'Any CPU'
#    configuration: '$(buildConfiguration)'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(publishDir)'
#    ArtifactName: 'drop'
#    publishLocation: 'Container'

trigger:
- main

pool:
  name: private

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  projectFolder: 'WebApplication5'  # 🔁 Change this to your project folder name
  publishDir: '$(Build.ArtifactStagingDirectory)\WebApp'

steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# 🛠️ Use robocopy to copy with timestamps preserved
- script: |
    robocopy "$(Build.SourcesDirectory)\$(projectFolder)" "$(publishDir)" /E /COPY:DAT /DCOPY:T /NFL /NDL /NJH /NJS
  displayName: 'Copy files with timestamps using robocopy (safe mode)'

# 📦 Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishDir)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
