trigger:
- main  # change to your branch name

pool:
  name: private

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  outputDir: '$(Build.ArtifactStagingDirectory)\App'

steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\WebApplication5\bin\$(buildConfiguration)'  # Replace with your project path
    Contents: '**'
    TargetFolder: '$(outputDir)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDir)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
