trigger:
- main

pool:
  name: private

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  publishDir: '$(Build.ArtifactStagingDirectory)\_PublishedWebApp'

steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:PublishProfile="" /p:WebPublishMethod=FileSystem /p:PublishDir=$(publishDir)\ /p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishDir)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
